[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 10

[theme]
base = "dark"
primaryColor = "#00e5ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1c2333"
textColor = "#cce8f0"
