name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - dlib=19.24.2
  - numpy
  - scipy
  - pip
  - pip:
    - opencv-python-headless
    - streamlit
    - streamlit-webrtc
    - av
    - ultralytics==8.4.46 --no-deps
    - torch
    - torchvision
    - plotly
    - requests
    - matplotlib
    - psutil
    - pyyaml
    - polars
    - ultralytics-thop
