name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - dlib=19.24.2
  - opencv
  - numpy
  - scipy
  - pip
  - pip:
    - streamlit
    - streamlit-webrtc
    - av
    - ultralytics==8.4.46
    - torch
    - torchvision
    - plotly
    - requests
